fit:
  seed_everything: 13
  model: &model_ref
    class_path: cooler_b_cell.models.lit.EpitopeLit
    init_args:
      lr: 0.001
      skip_egnn: False
      skip_rnn: False
      esm_model_name: esm2_t30_150M_UR50D
      esm_finetune: False
      esm_reduce_dim: 128
      egnn_num_layers: 2
      egnn_m_dim: 64
      egnn_num_nn: 0
      egnn_dropout: 0.0
      egnn_sparse_only: True
      egnn_soft_edges: True
      rnn_hidden_size: 64
      rnn_num_layers: 2
      rnn_bidirectional: True
      rnn_dropout: 0.0
      mlp_hidden_dim: 32
      mlp_dropout: 0.0
  data:
    class_path: cooler_b_cell.datasets.lit.EpitopeLit
    init_args:
      train_path: /data/scratch/aronto/cdrdock_data/data/train.jsonl
      dev_path: /data/scratch/aronto/cdrdock_data/data/dev.jsonl
      batch_size: 4
      esm_model_name: esm2_t30_150M_UR50D
      padded_length: 1024
  trainer:
    logger:
      class_path: pytorch_lightning.loggers.WandbLogger
      init_args:
        project: cooler_b_cell
        name: tiny
    callbacks:
      - class_path: pytorch_lightning.callbacks.ModelCheckpoint
        init_args:
          monitor: validation/auc
          dirpath: /data/scratch/aronto/b_cell_epitope/cooler_b_cell/ckpt
          filename: tiny
          auto_insert_metric_name: False
          mode: max
    accelerator: gpu
    devices: -1
    strategy: ddp
    log_every_n_steps: 10
    max_epochs: 50
test:
  seed_everything: 13
  model: *model_ref
  data:
    class_path: cooler_b_cell.datasets.lit.EpitopeLit
    init_args:
      test_path: /data/scratch/aronto/cdrdock_data/data/test.jsonl
      esm_model_name: esm2_t30_150M_UR50D
      padded_length: 1024
  trainer:
    logger: False
    accelerator: gpu
    devices: 1
    strategy: ddp
    max_epochs: 1
  ckpt_path: /data/scratch/aronto/b_cell_epitope/cooler_b_cell/ckpt/tiny.ckpt

